#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#
# require: gem install kramdown
# Usage: $ ./script/markdown2html
require 'kramdown'

src = "./TestFlightApp.markdown"
dst = "./TestFlightApp.html"

html = Kramdown::Document.new(File.read(src)).to_html
html.gsub!("../../raw/master", ".")

html = <<EOB
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta name="Format" content="complete" />
	</head>
  <body>
    #{html}
  </body>
</html>
EOB

File.open(dst, "w") do |f|
  f.write html
end
